### ISSUE TITLE
Establish Endpoints

### ISSUE THREAD

**Issue by ZachJordan** [emqu9067/3308-Group-Project#19]
Create endpoints in 'index.js' to use POST method to database. This should update the database every time a card is dealt to the player or the dealer.

**Comment by AACooper1** [comment]
Just about finished with this FTR. I've got /table/add_card_to_hand, /table/add_hand, /table/begin_session, and /table/end_session. All I need to do now is figure out how to convert a js timestamp to a postgres one.
